import {StyleSheet, I18nManager, Platform, Dimensions} from 'react-native';
import * as CONSTANT from '../constants/globalConstants';
I18nManager.forceRTL(false);
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  // Global
  globalContainer: {
    flex: 1,
    backgroundColor: CONSTANT.whiteColor,
  },
  globalContainerTwo: {
    flex: 1,
    backgroundColor: CONSTANT.grayColor,
  },
  cardRatingParent: {
    flexDirection: 'row',
    marginLeft: 10,
    alignItems: 'center',
  },
  cardratingTextStyle: {
    marginLeft: 8,
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  cardRatingViewTextStyle: {
    color: CONSTANT.shadeGrayColor,
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  ImagePickView: {
    backgroundColor: CONSTANT.grayColor,
    borderColor: CONSTANT.shadeGrayColor,
    borderStyle: 'dashed',
    paddingHorizontal: 15,
    paddingVertical: 25,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
    borderRadius: 8,
  },
  ImagePickPlacholder: {
    width: 100,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 6,
    height: 100,
  },
  ImagePickTextView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  ImagePickBlueText: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
  },
  ImagePickText: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  ImagePickTextDescription: {
    fontSize: 14,
    lineHeight: 24,
    textAlign: 'center',
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },

  // FormInput
  FormInputContainer: {
    marginTop: 5,
    marginBottom: 10,
    width: '100%',
    height: windowHeight / 16,
    borderBottomColor: CONSTANT.borderColor,
    borderRadius: 5,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
  },
  FormInput: {
    backgroundColor: CONSTANT.whiteColor,
    borderRadius: 6,
    paddingHorizontal: 10,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontSize: 17,
    color: '#062347',
    fontFamily: 'OpenSans-Regular',
    width: '90%',
  },

  // FormButton
  buttonContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 50,
    padding: 10,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },

  // Header
  headerMainView: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: CONSTANT.primaryColor,
  },
  headerDrawerIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerPhoto: {
    width: 45,
    height: 45,
    borderRadius: 45 / 2,
  },

  // multiSlect
  multiSlectstyleMainWrapper: {
    overflow: 'hidden',
    width: '100%',
  },
  multiSlectstyleDropdownMenuSubsection: {
    backgroundColor: CONSTANT.whiteColor,
    height: 70,
    paddingLeft: 10,
    paddingTop: 18,
  },

  // imageCarousel
  imageCarouselView: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  imageCarouselImage: {
    width: '100%',
    borderRadius: 10,
    height: 180,
    alignSelf: 'flex-end',
  },

  // MultiLineTextField
  MultiLineTextFieldView: {
    borderColor: '#E1E1E1',
    borderBottomWidth: 1,
    padding: 12,
  },
  MultiLineTextField: {
    height: '100%',
    borderRadius: 5,
    fontSize: 16,
    color: '#062347',
    fontFamily: 'Urbanist-Regular',
    textAlignVertical: 'top',
  },

  // CheckBox
  checkBoxMainView: {
    flexDirection: 'row',
    paddingVertical: 5,
    marginVertical: 5,
    alignItems: 'center',
  },
  checkBoxCheck: {
    width: 20,
    height: 20,
    backgroundColor: CONSTANT.primaryColor,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxUncheck: {
    width: 20,
    height: 20,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: CONSTANT.whiteColor,
  },
  checkBoxText: {
    fontSize: 16,
    fontFamily: 'OpenSans-Bold',
    marginLeft: 15,
    color: CONSTANT.fontColor,
  },
  checkBoxTextSearch: {
    fontSize: 16,
    fontFamily: 'OpenSans-Regular',
    marginLeft: 15,
    color: CONSTANT.fontColor,
  },

  // preloader
  preloaderMainView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CONSTANT.primaryColor,
  },

  // imagePreview
  imagePreviewImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  imagePreviewCross: {
    backgroundColor: '#000',
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // auth
  authButtonGoogleButtonStyle: {
    marginTop: 10,
    width: '100%',
    borderColor: CONSTANT.borderColor,
    height: 50,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authGoogleImageStyle: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  authGoogleTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    marginTop: 5,
    color: CONSTANT.secondaryColor,
  },
  authLastSectionStyle: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 15,
    alignItems: 'center',
  },
  authLastSectionTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    marginTop: 5,
    color: CONSTANT.primaryColor,
  },

  // login
  authIconContainer: {
    width: '100%',
    paddingBottom: 50,
    backgroundColor: CONSTANT.primaryColor,
    alignItems: 'center',
  },
  authIconSkipBtn: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 15,
    marginVertical: 10,
    marginHorizontal: 15,
    textAlign: 'right',
    lineHeight: 30,
    letterSpacing: 0.5,
    color: '#FFFFFF60',
  },
  authAppIconStyleOne: {
    height: 140,
    width: 140,
    borderRadius: 140 / 2,
    backgroundColor: '#FFFFFF40',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authAppIconStyleTwo: {
    height: 120,
    width: 120,
    borderRadius: 120 / 2,
    backgroundColor: '#FFFFFF60',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authAppIconStyleThree: {
    height: 100,
    width: 100,
    borderRadius: 100 / 2,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authIconText: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    marginTop: 20,
    marginHorizontal: 15,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.whiteColor,
  },
  authText: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 22,
    marginVertical: 10,
    lineHeight: 30,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  authOrTextLine: {
    width: '100%',
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    marginVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authOrText: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 18,
    marginTop: -10,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    backgroundColor: CONSTANT.whiteColor,
    paddingHorizontal: 10,
  },
  loginRBsheetStyle: {
    backgroundColor: CONSTANT.whiteColor,
    height: '100%',
    borderRadius: 15,
    overflow: 'hidden',
  },
  loginRBSheetStatusView: {
    paddingHorizontal: 25,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 30,
  },
  loginRBSheetStatusIconView: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    alignItems: 'center',
    marginTop: 20,
    justifyContent: 'center',
  },
  loginRBSheetStatusHeading: {
    fontSize: 28,
    marginTop: 20,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
  },
  loginRBSheetStatusDescription: {
    fontSize: 16,
    marginTop: 20,
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
  },
  loginRBSheetStatusButonView: {
    marginVertical: 20,
    width: '100%',
  },
  loginRBSheetStatusCancelButton: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1.5,
    paddingVertical: 10,
    width: '100%',
    borderRadius: 4,
  },
  loginRBSheetStatusCancelButtonText: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 18,
    color: CONSTANT.shadeGrayColor,
    lineHeight: 26,
    textAlign: 'center',
  },

  // Signup
  signupTermsAndConditionText: {
    fontSize: 15,
    fontFamily: 'OpenSans-Regular',
    marginLeft: 10,
    color: CONSTANT.secondaryColor,
  },
  signupTermsAndConditionTextLast: {
    fontSize: 15,
    fontFamily: 'OpenSans-Regular',
    marginLeft: 10,
    color: CONSTANT.blueColor,
  },
  signupIconText: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    marginTop: 20,
    marginHorizontal: 15,
    lineHeight: 26,
    textAlign: 'center',
    letterSpacing: 0.5,
    color: CONSTANT.whiteColor,
  },

  // home
  homeSearchParentInputStyle: {
    borderBottomColor: '#E1E1E1',
    borderBottomWidth: 0.6,
    paddingVertical: Platform.OS == 'ios' ? 10 : 0,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeSearchIconStyle: {width: '10%', textAlign: 'center'},
  homeSearchInputStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    color: CONSTANT.whiteColor,
    width: '90%',
  },
  narrowSearchInputStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    color: CONSTANT.fontColor,
    width: '90%',
  },
  homeSearchCateogryParentStyle: {
    borderBottomColor: '#E1E1E1',
    marginBottom: 15,
    borderBottomWidth: 0.6,
    paddingVertical: Platform.OS == 'ios' ? 10 : 5,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeSearchCateogryTextStyle: {
    width: '80%',
    color: CONSTANT.shadeGrayColor,
    fontSize: 15,
    fontFamily: 'OpenSans-Regular',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  homeSearchSelectedCateogryText: {
    width: '80%',
    color: CONSTANT.whiteColor,
    fontSize: 16,
    fontFamily: 'OpenSans-SemiBold',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  homeCatHeadingTextStyle: {
    color: CONSTANT.fontColor,
    fontSize: 18,
    fontFamily: 'Urbanist-SemiBold',
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  homeCatExploreTextStyle: {
    fontSize: 14,
    fontFamily: 'Urbanist-Regular',
    lineHeight: 24,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  homefreelancerImageBackgroundStyle: {
    width: 50,
    height: 50,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  homefreelancerImageEditIconStyle: {
    backgroundColor: '#22C55E',
    width: 15,
    height: 15,
    borderRadius: 15 / 2,
    borderColor: CONSTANT.whiteColor,
    borderWidth: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hometaskImageBackgroundStyle: {
    height: 120,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  homeCatParentStyle: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    padding: 10,
  },
  homeTextContainer: {
    backgroundColor: CONSTANT.primaryColor,
    width: '100%',
    padding: 15,
  },
  homeTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.whiteColor,
  },
  homeTextStyleTwo: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 28,
    lineHeight: 38,
    letterSpacing: 0.5,
    color: CONSTANT.whiteColor,
  },
  homeFreelancerUnderLine: {
    borderBottomColor: '#DDD',
    borderBottomWidth: 1,
    width: '100%',
    marginVertical: 15,
  },
  // Custom Drawer
  drawerMainStyle: {flex: 1},
  drawerGuestHeaderParent: {
    backgroundColor: CONSTANT.secondaryColor,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerUserHeaderParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  draweruserImageHeaderStyle: {
    width: 60,
    height: 60,
    borderRadius: 60 / 2,
    borderWidth: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#dddddd90',
  },
  drawerUserImageStyle: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
  },
  draweruserDetailParentStyle: {marginLeft: 10},
  drawerNameStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  drawerManageProfileTextStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 12,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
    marginRight: 10,
  },
  drawerSeparatorStyle: {
    borderBottomColor: '#EEE',
    borderBottomWidth: 1,
    width: '100%',
  },
  drawerHeadingStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    marginLeft: 15,
  },
  drawerItemParentStyle: {
    flexDirection: 'row',
    marginLeft: 15,
    alignItems: 'center',
    marginTop: 15,
  },
  drawerItemTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    color: CONSTANT.fontColor,
  },
  drawerFooterParentStyle: {
    flexDirection: 'row',
    width: '100%',
    height: 40,
    marginTop: 10,
  },
  drawerFooterItemParentStyle: {
    width: '33.33%',
    borderTopColor: '#EEE',
    borderRightColor: '#EEE',
    borderRightWidth: 1,
    borderTopWidth: 1,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerFooterItemStyle: {
    height: 8,
    width: 8,
    borderRadius: 8 / 2,
    backgroundColor: '#EF4444',
    alignSelf: 'flex-end',
    marginRight: -30,
  },
  drawerLogoutParentStyle: {
    flexDirection: 'row',
    marginLeft: 15,
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
  },
  drawerLogoutTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: '#EF4444',
    marginLeft: 15,
  },
  drawerWalletContainer: {
    backgroundColor: CONSTANT.whiteColor,
    paddingHorizontal: 10,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  drawerCreditCard: {
    padding: 15,
    backgroundColor: '#D4DFF5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerCreditBlance: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.primaryColor,
    marginRight: 10,
  },
  drawerSettingConatiner: {
    backgroundColor: CONSTANT.grayColor,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 10,
  },
  drawerSettingSeprater: {
    height: 20,
    borderLeftWidth: 2,
    borderLeftColor: '#ddd',
    marginLeft: 2,
  },
  drawerSubSettingsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerSubSettingsIconStyle: {
    height: 8,
    width: 8,
    borderRadius: 8 / 2,
    borderWidth: 1,
  },

  // Category card
  catCardParentStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    width: 100,
  },
  catCardImageStyle: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
  },

  // Freelancer card
  freelancerCardParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: CONSTANT.whiteColor,
    paddingVertical: 15,
  },
  freelancerCardTitleParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  freelancerCardTitleStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  freelancerStartingTextStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
  },
  freelancingCardPriceStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },

  // Task card
  taskFeaturedBadgeParent: {
    backgroundColor: CONSTANT.primaryColorTwo,
    paddingHorizontal: 5,
  },
  taskFeaturedTextStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  taskNameStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
  },
  taskTitleStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  taskRatingMainStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  taskRatignParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskPriceParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskPriceStartignStyle: {
    color: CONSTANT.shadeGrayColor,
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
  },
  taskPriceStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },

  // Search result
  searchResultTitleParentStyle: {
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchResultTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  searchResultIconParentStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CONSTANT.grayColor,
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
  },
  serachResultNoItemView: {margin: 20, alignItems: 'center'},
  serachResultNoItemHeading: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 22,
    marginTop: 5,
    color: CONSTANT.fontColor,
    lineHeight: 30,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  serachResultNoItemDescription: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 22,
    marginTop: 5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  // narrowSearch
  narrowSearchHeaderView: {
    height: 70,
    backgroundColor: CONSTANT.grayColor,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  narrowSearchHeaderIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  narrowSearchHeaderText: {
    color: CONSTANT.fontColor,
    fontWeight: '700',
    fontSize: 18,
  },
  narrowSearchIconStyle: {
    width: '10%',
    textAlign: 'right',
  },
  narrowSearchCateogryTextStyle: {
    width: '90%',
    fontSize: 15,
    fontFamily: 'OpenSans-Regular',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  narrowSearchSubCateogryArray: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: '#EEEEEE',
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  narrowSearchPriceRatingHeading: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 20,
  },
  narrowSearchPriceAmount: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  narrowSearchPriceText: {
    color: CONSTANT.fontColor,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Urbanist-Bold',
  },
  narrowSearchPriceTextAmount: {
    color: CONSTANT.fontColor,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Urbanist-Regular',
  },
  narrowSearchRangeSlider: {
    width: '100%',
    height: 70,
    marginTop: -30,
  },
  narrowSearchHeadingText: {
    color: CONSTANT.fontColor,
    fontSize: 16,
    lineHeight: 26,
    marginTop: 20,
    fontFamily: 'Urbanist-Bold',
  },
  narrowSearchButtonView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  narrowSearchClearButton: {
    color: CONSTANT.shadeGrayColor,
    fontSize: 16,
    lineHeight: 26,
    marginVertical: 15,
    fontFamily: 'Urbanist-Bold',
  },
  narrowSearchInputView: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
  },
  narrowSearchCateogryConatiner: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    marginTop: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  narrowSearchLocationConatiner: {
    marginVertical: 10,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },
  // Profile detail
  profileParentStyle: {
    flex: 1,
    backgroundColor: CONSTANT.grayColor,
  },
  profileMainViewStyle: {
    backgroundColor: CONSTANT.whiteColor,
    borderTopColor: '#ddd',
    borderTopWidth: 1,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    borderLeftColor: '#ddd',
    borderLeftWidth: 1,
    borderRightColor: '#ddd',
    borderRightWidth: 1,
    marginTop: 50,
    paddingBottom: 10,
  },
  profileImageBackgrounfStyle: {
    width: 80,
    height: 80,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    alignSelf: 'center',
  },
  profileOnlineStatusStyle: {
    backgroundColor: '#22C55E',
    width: 15,
    height: 15,
    borderRadius: 15 / 2,
    borderColor: CONSTANT.whiteColor,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  profileNameStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
    textAlign: 'center',
    marginVertical: 5,
  },
  profileTitleStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
  },
  profileViewsParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  profileTopHeadingStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 5,
  },
  profileHeadingValueStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    textAlign: 'center',
  },
  profileSaveParentStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 15,
  },
  profileSaveTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    textAlign: 'center',
    marginLeft: 10,
  },
  profileSectionHeadingStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginVertical: 10,
    marginHorizontal: 10,
  },
  profileQualificationCardParentStyle: {
    marginHorizontal: 10,
    marginBottom: 15,
  },
  profileQualificationCardInstituteTitleStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  profileQualificationCardTitleStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  profileQualificationCardDateStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  profileTaskCardParentStyle: {
    marginHorizontal: 10,
    marginBottom: 15,
    overflow: 'hidden',
  },
  profileTaskCardCatStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
  },
  profiletaskCardBottomRowParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  profileTaskCardSalesIconParentStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: '#9B59B610',
    borderRadius: 5,
  },
  profileTaskCardIconMainTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginHorizontal: 10,
  },
  profileBottomRowIcontitleStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginHorizontal: 10,
  },
  profiledeliveryIconStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: '#1ABC9C10',
    borderRadius: 5,
  },

  // Earnings
  earningTabMainStyle: {
    backgroundColor: CONSTANT.whiteColor,
    flexDirection: 'row',
    padding: 10,
    marginHorizontal: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 4,
    marginBottom: 10,
  },
  earningTextParentStyle: {flexDirection: 'row', alignItems: 'center'},
  earningIncomIconStyle: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#18B99B20',
  },
  earningTextBoldStyle: {
    fontFamily: 'Urbanist-Bold',
    color: CONSTANT.fontColor,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  earningWithdrawIconStyle: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7357FB20',
  },
  earningIncomPendingIconStyle: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF616720',
  },
  earningAvailableBalanceStyle: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#309CFF20',
  },
  earningTabTextStyle: {
    fontFamily: 'OpenSans-Regular',
    color: CONSTANT.shadeGrayColor,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  earningPaymentMethodStyle: {
    fontFamily: 'Urbanist-Bold',
    color: CONSTANT.fontColor,
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    margin: 15,
  },
  earningPayoutSettingTabParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 15,
    marginVertical: 10,
    alignItems: 'center',
  },
  earningSeparatorStyle: {
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    height: 18,
    width: 18,
    borderRadius: 18 / 2,
  },
  earningPayoutImageStyle: {width: 25, height: 25, marginLeft: 10},
  earningPayoutTextHeadingStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 10,
    color: CONSTANT.fontColor,
  },
  earningPayoutParagraphText: {
    fontFamily: 'OpenSans-Regular',
    color: CONSTANT.shadeGrayColor,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginHorizontal: 15,
    marginBottom: 15,
  },
  earningPayoneerTextParentStyle: {
    borderColor: '#22C55E',
    borderWidth: 4,
    height: 18,
    width: 18,
    borderRadius: 18 / 2,
  },
  earningPayoutSeparatorStyle: {
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    width: '100%',
    marginTop: 15,
    marginBottom: 15,
  },
  earningPolicyTextStyle: {
    fontFamily: 'OpenSans-Regular',
    color: CONSTANT.blueColor,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginHorizontal: 15,
    marginBottom: 15,
  },

  // Footer
  footerParentStyle: {
    backgroundColor: CONSTANT.secondaryColor,
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerMainTextStyle: {
    color: '#FFD101',
    marginTop: 20,
    fontSize: 28,
    lineHeight: 38,
    letterSpacing: 0.5,
    fontFamily: 'Urbanist-Bold',
  },
  footerTaglineTextStyle: {
    color: CONSTANT.whiteColor,
    marginHorizontal: 25,
    marginVertical: 20,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: 'OpenSans-Regular',
  },
  footerButtonParentStyle: {
    width: '100%',
    paddingHorizontal: 10,
    paddingBottom: 20,
  },

  // Payout history
  historyParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 15,
    margin: 15,
    borderRadius: 5,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
  },
  historyMainRowParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyRegularTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  historyBoldTextStyle: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  historyStatusParentStyle: {
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 60,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  historyStatusTextStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  historyPayoutSeparatorStyle: {
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    width: '100%',
    marginTop: 15,
    marginBottom: 15,
  },

  // Invoices
  invoiceParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 15,
    margin: 15,
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  invoicePayoutSeparatorStyle: {
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    width: '100%',
    marginTop: 15,
    marginBottom: 15,
  },
  invoiceRowParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  invoiceLableTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  invoiceValueTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  invoiceClientNameValueTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.blueColor,
    width: '60%',
    textAlign: 'right',
  },
  invoiceDownloadParentStyle: {
    alignSelf: 'center',
    padding: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  incoiceDownloadTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.blueColor,
    marginRight: 10,
  },
  invoiceInfoTextParentStyle: {
    backgroundColor: '#FFED99',
    padding: 15,
    width: '100%',
  },
  invoiceInfoTextStyle: {
    textAlign: 'center',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: '#997D01',
  },
  invoiceEmptyView: {
    flex: 1,
    alignItems: 'center',
    alignContent: 'center',
    marginTop: -40,
  },
  invoiceEmptyImg: {
    width: 250,
    height: 250,
    marginTop: '50%',
  },
  invoiceEmptyText: {
    color: CONSTANT.fontColor,
    fontSize: 18,
    marginVertical: 10,
    fontFamily: 'Urbanist-SemiBold',
  },
  // RBSheet
  RBSheetheaderStyle: {
    backgroundColor: CONSTANT.grayColor,
    height: 60,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  RBSheetheaderStyleTwo: {
    backgroundColor: CONSTANT.grayColor,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
  },
  RBSheetCloseIconStyle: {
    width: '10%',
    textAlign: 'center',
  },
  RBSheetHeaderTextStyle: {
    color: CONSTANT.fontColor,
    fontSize: 18,
    lineHeight: 26,
    textAlign: 'center',
    fontFamily: 'Urbanist-Bold',
  },
  RBSheetParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    height: '100%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    overflow: 'hidden',
  },
  RBSheetParentStyleTwo: {
    backgroundColor: CONSTANT.whiteColor,
    height: '100%',
    borderRadius: 15,
    overflow: 'hidden',
  },

  //homeRBSheetSearchStyle
  homeRBSheetSearchStyle: {
    borderColor: '#E1E1E1',
    margin: 15,
    paddingHorizontal: 10,
    borderWidth: 0.6,
    paddingVertical: Platform.OS == 'ios' ? 10 : 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeRBSheetSearchTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    color: CONSTANT.fontColor,
    width: '90%',
    marginLeft: 10,
  },
  homeRBSheetListTextStyle: {
    color: CONSTANT.fontColor,
    fontFamily: 'OpenSans-Bold',
    fontSize: 15,
    lineHeight: 24,
    paddingVertical: 10,
    width: '100%',
  },

  // Dashboard
  dashboardTabContainer: {
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-between',
  },
  dashboardTabsInner: {
    backgroundColor: CONSTANT.whiteColor,
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 15,
    justifyContent: 'space-between',
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  dashboardTabsText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    color: CONSTANT.fontColor,
    lineHeight: 26,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  dashboardTabsNotification: {
    height: 8,
    width: 8,
    borderRadius: 8 / 2,
    backgroundColor: '#EF4444',
  },
  dashboardServicesContainer: {
    backgroundColor: CONSTANT.whiteColor,
    flexDirection: 'row',
    padding: 10,
    marginHorizontal: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 4,
    marginBottom: 10,
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  dashboardServices2Rgb: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7357FB20',
  },
  dashboardServices3Rgb: {
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF616720',
  },
  dashboardServicestext1: {
    fontFamily: 'Urbanist-Bold',
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  dashboardServicestext2: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  dashboardUserProfile: {
    flexDirection: 'row',
    padding: 10,
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: CONSTANT.whiteColor,
  },
  dashboardUserProfileNameConatiner: {
    marginLeft: 15,
  },
  dashboardUserProfileName: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  dashboardUserProfileAccount: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
  },
  dashboardUserProfileIcon: {
    paddingHorizontal: 5,
    backgroundColor: CONSTANT.grayColor,
    height: 50,
    width: 50,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardFooterParentStyle: {
    backgroundColor: '#9B59B620',
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  dashboardFooterMainTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    textAlign: 'center',
    color: CONSTANT.secondaryColor,
  },
  dashboardfooterTaglineTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    textAlign: 'center',
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  dashboardfooterButtonParentStyle: {
    width: '100%',
    paddingHorizontal: 40,
    paddingBottom: 20,
  },
  dashboardGraphText: {
    alignSelf: 'flex-start',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    // textAlign: 'center',
    color: CONSTANT.secondaryColor,
  },

  // Tasks
  taskSearchConatiner: {
    flexDirection: 'row',
    marginHorizontal: 10,
    marginVertical: 10,
    justifyContent: 'space-between',
    borderBottomColor: '#ddd',
    borderBottomWidth: 0.5,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  taskSelectView: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },
  avaliableTaskCardParent: {
    backgroundColor: CONSTANT.whiteColor,
    margin: 10,
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  avaliableTaskCardContainer: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    alignItems: 'flex-start',
  },
  avaliableTaskCardStatus: {
    backgroundColor: '#F97316',
    paddingHorizontal: 10,
  },
  avaliableTaskCardStatusText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.whiteColor,
  },
  avaliableTaskCardSkills: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    color: CONSTANT.blueColor,
  },
  avaliableTaskCardTagLine: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  avaliableTaskCardProcessConatiner: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  avaliableTaskCardProcessText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  avaliableTaskCardProcessText2: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  avaliableTaskCardUserInfoMain: {
    flexDirection: 'row',
    borderColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
    justifyContent: 'space-between',
  },
  avaliableTaskCardUserInfoName: {
    flexDirection: 'row',
    paddingLeft: 10,
  },
  avaliableTaskCardUserInfoNameText1: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  avaliableTaskCardUserInfoNameText2: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },

  // taskDetail
  taskDetailHeaderView: {
    height: 70,
    backgroundColor: CONSTANT.grayColor,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  taskDetailDataView: {
    paddingHorizontal: 10,
    paddingTop: 15,
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    backgroundColor: CONSTANT.grayColor,
    alignItems: 'flex-start',
  },
  taskDetailFeatureTag: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    backgroundColor: CONSTANT.primaryColorTwo,
    paddingHorizontal: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.fontColor,
  },
  taskDetailSkillList: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    marginTop: 5,
    color: CONSTANT.blueColor,
  },
  taskDetailMainHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.fontColor,
  },
  taskDetailViewRating: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskDetailEyeIcon: {
    paddingLeft: 10,
    paddingRight: 5,
  },
  taskDetailDescriptionText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.secondaryColor,
  },
  taskDetailPlansMainView: {
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    backgroundColor: CONSTANT.whiteColor,
    flexDirection: 'row',
  },
  taskDetailPlansSingleView: {
    width: '33.3%',
    paddingVertical: 15,
    borderBottomColor: CONSTANT.borderColor,
    borderRightColor: CONSTANT.borderColor,
    borderRightWidth: 1,
  },
  taskDetailPlansSingleViewText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 23,
    color: CONSTANT.fontColor,
  },
  taskDetailPlansBodyView: {
    backgroundColor: CONSTANT.whiteColor,
    paddingHorizontal: 10,
    paddingTop: 20,
    paddingBottom: 10,
  },
  taskDetailPlansBodyImage: {
    width: 56,
    height: 56,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  taskDetailPlansBodyNameView: {
    marginLeft: 15,
    alignItems: 'flex-start',
  },
  taskDetailPlansBodyNameText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
  },
  taskDetailPlansBodyPriceText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 22,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 30,
    color: CONSTANT.primaryColor,
  },
  taskDetailPlansBodyDesc: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  taskDetailsubHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  taskDetailNoItemList: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: CONSTANT.whiteColor,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  taskDetailPlansPackageView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  taskDetailPlansPackageText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginHorizontal: 10,
  },
  taskDetailPlansPackageFeatureView: {
    flexDirection: 'row',
    marginVertical: 15,
  },
  taskDetailPlansPackageFeature: {
    width: '33.33%',
    paddingVertical: 5,
    borderRightColor: CONSTANT.borderColor,
    borderRightWidth: 1,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskDetailPlansPackageFeatureLast: {
    width: '33.33%',
    paddingVertical: 5,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskDetailPlansPkgFeatureIconOne: {
    width: 46,
    height: 46,
    backgroundColor: '#6366F120',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  taskDetailPlansPkgFeatureIconTwo: {
    width: 46,
    height: 46,
    backgroundColor: '#F9731620',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  taskDetailPlansPkgFeatureIconThree: {
    width: 46,
    height: 46,
    backgroundColor: '#22C55E20',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  taskDetailPlansPkgFeatureText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
    marginTop: 5,
  },
  taskDetailPlansPkgFeatureTextTwo: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    color: CONSTANT.fontColor,
  },
  taskDetailServicesView: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    paddingVertical: 20,
    width: '100%',
  },
  taskDetailServicesViewLast: {
    paddingVertical: 20,
    width: '100%',
  },
  taskDetailServicesPrice: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 26,
    color: CONSTANT.primaryColor,
  },
  taskDetailServicesDesc: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  taskDetailFAQView: {
    backgroundColor: CONSTANT.whiteColor,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 8,
    width: '100%',
    padding: 10,
    marginBottom: 10,
  },
  taskDetailFAQViewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskDetailFAQHeadingText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    width: '90%',
    lineHeight: 26,
    color: CONSTANT.fontColor,
    marginVertical: 10,
  },
  taskDetailFAQHeadingView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  taskDetailFAQBodyText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  taskDetailServicesNameText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    width: '80%',
    color: CONSTANT.secondaryColor,
  },
  taskDetailReviewHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  taskDetailReviewHeadingValue: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
    marginHorizontal: 10,
  },
  taskDetailReviewItemHeader: {
    backgroundColor: CONSTANT.whiteColor,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 8,
    width: '100%',
    padding: 10,
    paddingVertical: 15,
    marginBottom: 10,
  },
  taskDetailReviewItemImage: {
    width: 40,
    height: 40,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  taskDetailReviewItemHeading: {
    width: '85%',
    paddingHorizontal: 15,
  },
  taskDetailReviewItemHeadingText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  taskDetailReviewItemStarText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    color: CONSTANT.fontColor,
    marginHorizontal: 10,
  },
  taskDetailReviewItemTimeText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    color: CONSTANT.shadeGrayColor,
    marginHorizontal: 10,
  },
  taskDetailReviewReplyView: {
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    alignItems: 'flex-start',
    paddingVertical: 10,
  },
  taskDetailReviewReplyTag: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    backgroundColor: '#EEEEEE',
    paddingHorizontal: 10,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.fontColor,
  },
  taskDetailReviewReplyText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
    marginTop: 7,
  },
  taskDetailReviewReplyTimeView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  taskDetailReviewReplyTimeText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    color: CONSTANT.shadeGrayColor,
    marginHorizontal: 10,
  },
  taskDetailStatusTextHeading: {
    color: CONSTANT.fontColor,
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },

  // orderDetail
  orderDetailVerificationView: {
    backgroundColor: '#F9641230',
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  orderDetailVerificationHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
  },
  orderDetailVerificationWalletDesc: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  orderDetailNameView: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'flex-start',
  },
  orderDetailSkillListText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    letterSpacing: 0.5,
    lineHeight: 23,
    marginTop: 5,
    color: CONSTANT.blueColor,
  },
  orderDetailNameText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.fontColor,
  },
  orderDetailRatingView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderDetailFeaturesView: {
    backgroundColor: CONSTANT.whiteColor,
    paddingHorizontal: 10,
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    paddingTop: 20,
    paddingBottom: 10,
  },
  orderDetailFeaturesHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginBottom: 10,
  },
  orderDetailFeaturesListView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  orderDetailFeaturesListText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginHorizontal: 10,
  },
  orderDetailServicesView: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'flex-start',
  },
  orderDetailServicesHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  orderDetailServicesListView: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    paddingVertical: 20,
    width: '100%',
  },
  orderDetailServicesListViewLast: {
    paddingVertical: 20,
    // width: '100%',
  },
  orderDetailServicesListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orderDetailServicesListTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'left',
    lineHeight: 26,
    marginHorizontal: 10,
    color: CONSTANT.secondaryColor,
  },
  orderDetailServicesListPrice: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    // textAlign: 'right',
    lineHeight: 26,
    color: CONSTANT.primaryColor,
    // paddingLeft:20,
  },
  orderDetailServicesListDesc: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginVertical: 10,
  },
  orderDetailPlanView: {
    backgroundColor: CONSTANT.whiteColor,
    paddingVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomColor: CONSTANT.whiteColor,
  },
  orderDetailHeadingOrder: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    marginHorizontal: 10,
    color: CONSTANT.secondaryColor,
    marginBottom: 10,
  },
  orderDetailPlanSelectedPlan: {
    backgroundColor: CONSTANT.grayColor,
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  orderDetailPlanSelectedPlanView: {
    flexDirection: 'row',
    width: '90%',
  },
  orderDetailPlanSelectedPlanImage: {
    width: 56,
    height: 56,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  orderDetailPlanSelectedPlanTitleView: {
    marginLeft: 20,
    alignItems: 'flex-start',
  },
  orderDetailPlanSelectedPlanTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
  },
  orderDetailPlanSelectedPlanPrice: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 22,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 30,
    color: CONSTANT.primaryColor,
  },
  orderDetailSelectPlanMainView: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    flexDirection: 'row',
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orderDetailSelectPlanCheckCircle: {
    marginRight: 20,
    width: 25,
    height: 25,
    borderRadius: 25 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  orderDetailSelectPlanCheckInnerCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderDetailSelectPlanName: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginLeft: 10,
  },
  orderDetailSelectPlanPrice: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
  },
  orderDetailAdditionalfeatureView: {
    paddingHorizontal: 10,
    marginTop: 10,
  },
  orderDetailAdditionalfeatureHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginBottom: 10,
  },
  orderDetailAdditionalfeatureListText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginBottom: 10,
    width: '80%',
  },
  orderDetailAdditionalfeatureListTextValue: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.secondaryColor,
    marginBottom: 10,
  },
  orderDetailAdditionalfeatureSeparator: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    marginBottom: 10,
  },
  orderDetailWalletView: {
    backgroundColor: '#FEECA1',
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  orderDetailWalletHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.secondaryColor,
    marginHorizontal: 15,
  },

  // profileSetting
  profileSettingParentStyle: {
    flex: 1,
    backgroundColor: CONSTANT.grayColor,
  },
  profileSettingMainViewParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 10,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    border: 15,
  },
  profileSettingDropDownHeadingStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginTop: 10,
    marginLeft: 5,
  },
  profileSettingDropDownTextParent: {
    flexDirection: 'row',
    marginVertical: 20,
    justifyContent: 'space-between',
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  profileSettingDropDownTextStyle: {
    fontSize: 17,
    color: '#888888',
    fontFamily: 'OpenSans-Regular',
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  profileSettingSellerTypeConatiner: {
    marginVertical: 10,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },
  profileSettingenglishLevel: {
    marginVertical: 10,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },
  profileSettingEducation: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 10,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 15,
    border: 15,
    marginTop: 20,
  },
  profileDescriptionTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    marginTop: 10,
    marginLeft: 5,
  },
  educationListParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    paddingBottom: 10,
  },
  educationTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginLeft: 5,
  },
  addNewTextStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.blueColor,
    marginLeft: 5,
  },
  educationCardParentStyle: {
    paddingTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  educationCardParentStyleLast: {
    paddingTop: 20,
  },
  educationDescStyle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 13,
    lineHeight: 23,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  educationTitleStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  eduRemoveTextStyle: {
    textAlign: 'center',
    color: CONSTANT.shadeGrayColor,
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  eduRBChooseDateStyle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    marginTop: 10,
    marginLeft: 5,
  },
  eduRBStartDateStyle: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 15,
    justifyContent: 'space-between',
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  eduRBDateFromStyle: {
    fontSize: 17,
    color: CONSTANT.fontColor,
    fontFamily: 'OpenSans-Regular',
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  eduRBDateToParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  eduRBDateToTextStyle: {
    fontSize: 17,
    color: CONSTANT.fontColor,
    fontFamily: 'OpenSans-Regular',
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  eduRBDescStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
  },

  // billingInformation
  billingInformationConatiner: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 10,
    border: 15,
  },
  billingInformationCountry: {
    marginVertical: 10,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },
  billingInformationBtn: {
    paddingHorizontal: 10,
    paddingBottom: 10,
  },

  // identityInformation
  identityInformationConatiner: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 10,
    border: 15,
  },

  // savedItem
  savedItemMainView: {
    borderTopColor: CONSTANT.borderColor,
    borderTopWidth: 1,
    backgroundColor: CONSTANT.whiteColor,
    flexDirection: 'row',
  },
  savedItemSingleView: {
    width: '50%',
    paddingVertical: 15,
    borderBottomColor: CONSTANT.borderColor,
    borderRightColor: CONSTANT.borderColor,
    borderRightWidth: 1,
  },
  savedItemSingleViewText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 23,
  },
  savedItemHiddenConatiner: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#EF4444',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },

  // availableTaskDetail
  availableTaskDetailTopView: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: 'flex-start',
    backgroundColor: CONSTANT.whiteColor,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
  },
  availableTaskDetailTagStatus: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    paddingHorizontal: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    marginTop: 5,
    color: CONSTANT.whiteColor,
  },
  availableTaskDetailDatePlanView: {
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    marginVertical: 15,
  },
  availableTaskDetailDatePlanText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  availableTaskDetailDatePlanValue: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  availableTaskDetailProfileView: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: CONSTANT.whiteColor,
  },
  availableTaskDetailProfileImage: {
    width: 50,
    height: 50,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  availableTaskDetailProfileHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.shadeGrayColor,
  },
  availableTaskDetailProfileName: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  availableTaskDetailTaskBudgetView: {
    backgroundColor: CONSTANT.whiteColor,
    paddingVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 10,
  },
  availableTaskDetailTaskBudgetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  availableTaskDetailTaskHistory: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: CONSTANT.whiteColor,
    alignItems: 'flex-start',
  },
  availableTaskDetailTaskHistoryImage: {
    width: 35,
    height: 35,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  availableTaskDetailTaskHistoryDate: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 26,
    color: CONSTANT.shadeGrayColor,
  },
  availableTaskDetailTaskHistoryFileImage: {
    marginRight: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  availableTaskDetailTaskHistoryMore: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    letterSpacing: 0.5,
    lineHeight: 24,
    color: CONSTANT.fontColor,
  },
  availableTaskDetailTaskHistoryDownload: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 24,
    color: CONSTANT.blueColor,
  },
  availableTaskDetailDocumentsView: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: CONSTANT.whiteColor,
    borderBottomColor: CONSTANT.whiteColor,
    alignItems: 'flex-start',
  },
  availableTaskDetailDocumentsStatus: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    color: CONSTANT.fontColor,
  },
  availableTaskDetailDocumentsAddedView: {
    backgroundColor: CONSTANT.grayColor,
    borderColor: '#eeeeee',
    borderRadius: 5,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    width: '100%',
    marginBottom: 10,
  },
  availableTaskDetailSelectedCircle: {
    marginRight: 10,
    width: 25,
    height: 25,
    borderRadius: 25 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
  },
  availableTaskDetailfeaturedViewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  availableTaskDetailfeaturedViewItemList: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  availableTaskDetailCustomFieldscontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  availableTaskDetailCustomFieldsView: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  availableTaskStatusConatiner: {
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    marginTop: 10,
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginBottom: -10,
    flexDirection: 'row',
    backgroundColor: '#6366F1',
  },
  availableTaskCompleted: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '15%',
    backgroundColor: CONSTANT.whiteColor,
    height: 50,
  },
  availableTaskPickDocView: {
    backgroundColor: CONSTANT.grayColor,
    borderColor: '#eeeeee',
    borderRadius: 5,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    marginBottom: 10,
  },
  availableTaskRatingConatiner: {
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 15,
    backgroundColor: CONSTANT.grayColor,
    marginVertical: 10,
  },
  availableTaskFeedBackView: {
    height: 170,
    marginVertical: 10,
    width: '100%',
  },
  // Identity information
  selectedDocCardParentStyle: {
    backgroundColor: CONSTANT.grayColor,
    borderColor: '#eeeeee',
    borderRadius: 5,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    borderRadius: 6,
    padding: 15,
    marginBottom: 10,
    marginHorizontal: 10,
  },
  selectedDocCardImageStyle: {
    width: 40,
    height: 40,
    marginBottom: 10,
  },
  selectedDocTitleParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectedDocTitleTextStyle: {
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  selectedDocSizeTextStyle: {
    fontSize: 14,
    lineHeight: 24,
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  identityDownloadsImageText: {
    color: CONSTANT.fontColor,
    fontSize: 16,
    marginTop: 10,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },

  // disputes
  disputesParentStyle: {
    backgroundColor: CONSTANT.whiteColor,
    padding: 15,
    margin: 15,
    borderRadius: 10,
    borderColor: CONSTANT.borderColor,
    borderWidth: 1,
    alignItems: 'flex-start',
  },
  disputesStatus: {
    borderColor: '#F97316',
    borderWidth: 1,
    paddingHorizontal: 15,
    marginVertical: 10,
  },
  disputesStatusText: {
    fontSize: 14,
    lineHeight: 24,
    fontFamily: 'Urbanist-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },

  // disputesDetails
  disputesDetailsContainer: {
    padding: 10,
    borderColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    paddingVertical: 15,
  },
  disputesDetailsInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  disputesDetailsInfoText1: {
    fontSize: 13,
    lineHeight: 23,
    fontFamily: 'Urbanist-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputesDetailsInfoText2: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputesDetailsInfoContainer2: {
    alignItems: 'flex-start',
  },
  disputesDetailsInfoTagLine: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputesDetailsUserContainer: {
    padding: 10,
    borderColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  disputesDetailsUserText: {
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
  },
  disputesDetailsUserName: {
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputesDetailsDescriptionContainer: {
    padding: 10,
    borderColor: CONSTANT.borderColor,
  },
  disputesDetailsDescriptionTagline: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputesDetailsDescription1: {
    fontSize: 15,
    lineHeight: 24,
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    paddingVertical: 10,
  },
  disputesDetailsDescriptionBtn: {
    fontSize: 15,
    lineHeight: 24,
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    paddingVertical: 10,
  },
  RBSheetReplyDisputeText: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    paddingVertical: 10,
  },
  RBSheetReplyDisputeDecription: {
    fontSize: 15,
    lineHeight: 24,
    fontFamily: 'OpenSans-Regular',
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
  },
  disputeDetailsReplyContainer: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingVertical: 10,
  },
  disputeDetailsReplyBtn: {
    width: '32%',
    backgroundColor: CONSTANT.shadeGrayColor,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  disputeDetailsReplyBtnText: {
    color: CONSTANT.whiteColor,
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },
  disputeDetailsRefundBtn: {
    width: '32%',
    backgroundColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  disputeDetailsRefundBtnText: {
    color: CONSTANT.whiteColor,
    textAlign: 'center',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },
  disputeDetailsDeclineBtn: {
    width: '32%',
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  disputeDetailsDeclineBtnText: {
    color: CONSTANT.whiteColor,
    textAlign: 'center',
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    fontFamily: 'Urbanist-SemiBold',
  },
  disputeDetailsAddReply: {
    height: 170,
    marginVertical: 10,
    width: '100%',
  },
  // Account settings
  accountSettingParent: {
    flex: 1,
    backgroundColor: CONSTANT.grayColor,
  },
  accountLostPasswordParentStyle: {
    padding: 10,
    backgroundColor: CONSTANT.whiteColor,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderLeftColor: '#ddd',
    borderRightColor: '#ddd',
    borderLeftWidth: 1,
    borderRightWidth: 1,
  },
  photoSettingparent: {
    backgroundColor: CONSTANT.grayColor,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 4,
    marginTop: 15,
  },
  photoSettingTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    width: '80%',
  },
  disableAccountParentStyle: {
    backgroundColor: CONSTANT.grayColor,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 4,
    marginTop: 10,
  },
  disableAccountTextStyle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: CONSTANT.fontColor,
    width: '80%',
  },
  deactivateAccountParent: {
    padding: 10,
    backgroundColor: CONSTANT.whiteColor,
    borderTopColor: '#ddd',
    borderTopWidth: 1,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderLeftColor: '#ddd',
    borderRightColor: '#ddd',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    marginTop: 20,
  },
  accountSettingReasonStyle: {
    marginVertical: 10,
    borderBottomColor: CONSTANT.borderColor,
    borderBottomWidth: 1,
    width: '100%',
  },

  // RbSheetAddCredit
  RbSheetAddCreditDescConatainer: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  RbSheetAddCreditAsterisk: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: '#EF4444',
  },
  RbSheetAddCreditDescription: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: CONSTANT.shadeGrayColor,
    paddingHorizontal: 10,
  },

  // Nodata found
  NodataFoundContainer: {
    flex: 1,
    alignItems: 'center',
    alignContent: 'center',
  },
  NodataFoundImg: {
    width: 250,
    height: 250,
    marginTop: '45%',
  },
  NodataFoundText: {
    color: CONSTANT.fontColor,
    fontSize: 18,
    marginVertical: 10,
    fontFamily: 'Urbanist-SemiBold',
  },
});
